site_name: Ormdantic
site_description: A fast, async, and type-safe ORM for Python 3.10+ based on SQLAlchemy and Pydantic.
site_url: https://ormdantic.yezz.me/

theme:
  features:
    - header.autohide
  name: 'material'
  palette:
    - scheme: default
      primary: amber
      accent: orange
      toggle:
          icon: material/lightbulb
          name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: orange
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
  favicon: favicon.png
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
    logo: fontawesome/solid/database
repo_name: Yezz123/Ormdantic
repo_url: https://github.com/yezz123/ormdantic
edit_uri: ""

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tasklist
  - pymdownx.tabbed

plugins:
  - search
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(window.localStorage.getItem('/.__palette')).index == 1) ? 'dark' : 'light'
extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
  - About: index.md
  - installation.md
  - Usage: usage.md
  - Development - Contributing: contributing.md
  - Frequently Asked Questions: faq.md
  - Code of Conduct: code_of_conduct.md
  - License: license.md

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/yezz123
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/THyasser1
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/yezz123
  - icon: fontawesome/solid/globe
    link: https://yezz.me
